spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/aurora_data?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    password: ziyue.wang
    database: 1
    jedis:
      pool:
        min-idle: 10
        max-idle: 300
        max-active: 600
        max-wait: 1000
    timeout: 20000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aurora-calculation


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true

