spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/aurora_risk?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
  redis:
    timeout: 10000 #链接超时时间
    host: localhost
    port: 6379
    password: ziyue.wang
    database: 0
    lettuce:
      pool:
        max-active: 1024 #最大连接数
        max-wait: 1000 #最大连接阻塞等待时间（毫秒）
        max-idle: 200 #最大控线连接
        min-idle: 5 #最小空闲链接

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #熔断超时时间

ribbon:
  ReadTimeout: 60000  #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接超时时间
  MaxAutoRetries: 0 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1


